[GH-56] Update FredHutchAzureIdp x509_cert string (#57)
* Use the new FHCC x509 cert string

* install python3-saml in dev dependencies, but we always need it. also lxml and xmlsec need to be pinned for this to work.

* update version of black to fix ImportError: cannot import name '_unicodefun' from 'click'

* update version to pull in for update-pr-branch-version to fix No module named 'six.moves'

* [Bot] Update version to 1.2.9

---------

Co-authored-by: github-actions <41898282+github-actions[bot]@users.noreply.github.com>